//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> PublicationYr { get; set; }
        public Nullable<int> Condition { get; set; }
        public string Comment { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
